#!/usr/bin/env python3
"""Build a cell-exact webfont for the nanobots banner art.

milktea.txt is a FIGlet banner (phm-slanted.flf) in which every character is
meant to fill exactly one terminal cell: the sextants and block diagonals of
the Symbols for Legacy Computing block (U+1FB00..U+1FBFF), plus FULL BLOCK and
RIGHT HALF BLOCK. Noto Sans Symbols 2 draws each of those in a 1000x1000 unit
square, so one cell is one em — 6 rows of art are 6 em tall and never need
half-cell height packing.

Using the upstream font in HTML breaks the art three ways:

  * SPACE advances 260 units, a quarter of a cell, so every gap inside a word
    is too narrow and the rest of the line slides progressively left.
  * U+2588 and U+2590 are not in Noto Sans Symbols 2 at all, so the browser
    substitutes them from the fallback font, which has both a different
    advance width and a different cell design.
  * the whole font is ~200 KB of glyphs to draw 23 characters.

This script reads the art, keeps only the codepoints those files actually
contain, widens every retained glyph to one cell (recentring the outline of
any that was proportional, should the page ever grow a proportional glyph such
as an ASCII frame bar), and synthesises the missing block elements as
rectangles covering the same box as the sextants.

Vertical geometry needs no patching here: a cell is exactly one em tall from
the font's own metrics, so with line-height:1 the rows tile. Only the cell's
aspect is left to the page, which stretches the block to the 1:2 cell a
terminal gives these glyphs (index.html does that with transform: scaleY(2)).

Outputs, both committed, regenerated by `just gen-symbol-font`:

  examples/nanobots/milktea-symbols.woff2  the patched subset
  examples/nanobots/milktea-symbols.css    @font-face with the font inlined as
                                           a data: URI, so index.html renders
                                           when opened straight from disk (a
                                           file:// page cannot fetch a font)

The result is a modified copy of Noto Sans Symbols 2 (Copyright 2022 The Noto
Project Authors, https://github.com/notofonts/symbols), used under the SIL
Open Font License 1.1; the notice travels in the generated CSS.
"""

import base64
import re
import sys
from pathlib import Path

from fontTools import subset
from fontTools.misc.transform import Transform
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
EXAMPLE = ROOT / "examples" / "nanobots"
OUT_FONT = EXAMPLE / "milktea-symbols.woff2"
OUT_CSS = EXAMPLE / "milktea-symbols.css"

# The art is what decides the subset, so these are the sources of truth.
ART_TEXT = EXAMPLE / "milktea.txt"
ART_PAGE = EXAMPLE / "index.html"

# Where a source font might live, in preference order.
SOURCES = (
    "~/Library/Fonts/NotoSansSymbols2-Regular.ttf",
    "/Library/Fonts/NotoSansSymbols2-Regular.ttf",
    "/System/Library/Fonts/Supplemental/NotoSansSymbols2-Regular.ttf",
    "/usr/share/fonts/truetype/noto/NotoSansSymbols2-Regular.ttf",
    "/usr/share/fonts/noto/NotoSansSymbols2-Regular.ttf",
)

FAMILY = "Milktea Symbols"

# One terminal cell, in font units. The sextants advance 1000 and are drawn
# between these two y values, so a cell is also exactly one em tall.
CELL = 1000
CELL_TOP = 839
CELL_BOTTOM = -161

# Block elements the art uses that Noto Sans Symbols 2 does not draw. Each
# value is the rectangle to fill, sharing the sextants' cell box.
SYNTHESISED = {
    0x2588: (0, CELL_BOTTOM, CELL, CELL_TOP),  # FULL BLOCK
    0x2590: (CELL // 2, CELL_BOTTOM, CELL, CELL_TOP),  # RIGHT HALF BLOCK
}

NOTICE = (
    f'/* Generated by scripts/gen_symbol_font.py -- do not edit.\n'
    f" *\n"
    f" * {FAMILY} is a subset of Noto Sans Symbols 2, patched so that SPACE\n"
    f" * and every glyph this page uses advance exactly one terminal cell\n"
    f" * (1000 units), and with the block elements the art needs added as\n"
    f" * rectangles over the sextants' cell.\n"
    f" *\n"
    f" * Noto Sans Symbols 2 is Copyright 2022 The Noto Project Authors\n"
    f" * (https://github.com/notofonts/symbols) and licensed under the SIL\n"
    f" * Open Font License, Version 1.1 (https://scripts.sil.org/OFL).\n"
    f" *\n"
    f" * The font is inlined as a data: URI because a page opened with file://\n"
    f" * is not allowed to fetch a font from a sibling file.\n"
    f" */\n"
)


def find_source() -> Path:
    for candidate in SOURCES:
        path = Path(candidate).expanduser()
        if path.exists():
            return path
    raise SystemExit(
        "no Noto Sans Symbols 2 found; looked in:\n  "
        + "\n  ".join(SOURCES)
        + "\nInstall it (e.g. `brew install --cask font-noto-sans-symbols-2`) "
        "and retry."
    )


def used_codepoints() -> set:
    """Every character the banner needs, taken from the files that draw it."""
    codepoints = set(ART_TEXT.read_text(encoding="utf-8"))
    page = ART_PAGE.read_text(encoding="utf-8")
    for block in re.findall(r"<pre[^>]*>(.*?)</pre>", page, re.S):
        codepoints |= set(block)
    codepoints = {ord(c) for c in codepoints}
    codepoints -= {0x0A, 0x0D}  # line structure, not glyphs
    return codepoints


def load_subset(source: Path, codepoints: set) -> TTFont:
    options = subset.Options()
    # A cell-art font must not kern: the art assumes every glyph advances
    # exactly one cell, and the source's kerning would move the blocks.
    options.layout_features = []
    options.drop_tables += ["GSUB", "GPOS", "GDEF", "kern", "morx", "mort"]
    # No vertical layout: vmtx holds one metric per glyph and would need the
    # synthesised block elements added to it too.
    options.drop_tables += ["vhea", "vmtx", "ltag"]
    options.name_IDs = ["*"]
    options.name_legacy = True
    options.name_languages = ["*"]
    options.glyph_names = False
    options.recalc_bounds = True
    options.recalc_timestamp = False  # keep output reproducible
    options.canonical_order = True

    font = subset.load_font(str(source), options)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=sorted(codepoints))
    subsetter.subset(font)
    return font


def add_cmap(font: TTFont, codepoint: int, glyph_name: str) -> None:
    for table in font["cmap"].tables:
        if not table.isUnicode():
            continue
        if table.format == 4 and codepoint > 0xFFFF:
            continue
        table.cmap[codepoint] = glyph_name
        table.cmap = dict(sorted(table.cmap.items()))


def synthesise_block(font: TTFont, codepoint: int, box) -> str:
    x0, y0, x1, y1 = box
    pen = TTGlyphPen(None)
    pen.moveTo((x0, y0))
    pen.lineTo((x1, y0))
    pen.lineTo((x1, y1))
    pen.lineTo((x0, y1))
    pen.closePath()
    glyph = pen.glyph()

    name = "u%04X" % codepoint
    order = list(font.getGlyphOrder())  # copy: glyf shares the font's list
    order.append(name)
    font["glyf"][name] = glyph
    font.setGlyphOrder(order)
    font["hmtx"][name] = (CELL, 0)
    glyph.recalcBounds(font["glyf"])
    add_cmap(font, codepoint, name)
    return name


def widen_to_cell(font: TTFont, name: str) -> int:
    """Force one glyph to a single cell, returning the outline shift applied."""
    hmtx = font["hmtx"]
    glyf = font["glyf"]
    advance, _ = hmtx[name]
    if advance == CELL:
        return 0
    hmtx[name] = (CELL, 0)

    glyph = glyf[name]
    if glyph.numberOfContours == 0:
        return 0  # SPACE is empty; widening it is the whole point

    # Centre the outline in its new, wider cell.
    shift = int(round((CELL - advance) / 2))
    pen = TTGlyphPen(glyf)
    glyph.draw(TransformPen(pen, Transform(1, 0, 0, 1, shift, 0)), glyf)
    wider = pen.glyph()
    glyf[name] = wider
    wider.recalcBounds(glyf)
    return shift


def rename(font: TTFont) -> None:
    """Give the patched font its own family so it cannot be confused with the
    unpatched original, keeping the upstream copyright and licence records."""
    slug = FAMILY.replace(" ", "")
    values = {
        1: FAMILY,
        3: f"1.000;MLKT;{slug}-Regular",
        4: f"{FAMILY} Regular",
        5: "Version 1.000",
        6: f"{slug}-Regular",
    }
    for record in font["name"].names:
        if record.nameID in values:
            record.string = values[record.nameID].encode(record.getEncoding())


def patch(font: TTFont, codepoints: set) -> list:
    """Widen every glyph to one cell, adding the missing block elements."""
    notes = []
    cmap = font.getBestCmap()
    missing = sorted(codepoints - set(cmap))
    unexpected = sorted(set(missing) - set(SYNTHESISED))
    if unexpected:
        raise SystemExit(
            "; ".join("U+%04X" % cp for cp in unexpected)
            + " are used by the art but are in neither the font nor the "
            "synthesised block table"
        )

    for codepoint in sorted(codepoints):
        if codepoint in missing:
            name = synthesise_block(font, codepoint, SYNTHESISED[codepoint])
            notes.append((codepoint, name, "synthesised", 0))
            continue
        name = cmap[codepoint]
        advance, _ = font["hmtx"][name]
        shift = widen_to_cell(font, name)
        if advance != CELL:
            notes.append((codepoint, name, f"was {advance}", shift))
    return notes


def verify(font: TTFont, codepoints: set) -> None:
    """Every glyph must advance one cell and stay inside one cell box."""
    cmap = font.getBestCmap()
    for codepoint in sorted(codepoints):
        name = cmap[codepoint]
        advance, _ = font["hmtx"][name]
        if advance != CELL:
            raise SystemExit(f"U+{codepoint:04X} advances {advance}, not a cell")
        glyph = font["glyf"][name]
        if glyph.numberOfContours and (glyph.xMin < 0 or glyph.xMax > CELL):
            print(
                f"  note: U+{codepoint:04X} spans x {glyph.xMin}..{glyph.xMax}, "
                f"outside its cell"
            )


def write_css(path: Path, font_bytes: bytes) -> None:
    payload = base64.b64encode(font_bytes).decode("ascii")
    path.write_text(
        NOTICE
        + "@font-face {\n"
        + f'  font-family: "{FAMILY}";\n'
        + "  font-style: normal;\n"
        + "  font-weight: 400;\n"
        + "  font-display: block;\n"
        + f'  src: url(data:font/woff2;base64,{payload}) format("woff2");\n'
        + "}\n",
        encoding="utf-8",
    )


def main() -> int:
    source = find_source()
    codepoints = used_codepoints()
    font = load_subset(source, codepoints)
    notes = patch(font, codepoints)
    verify(font, codepoints)
    rename(font)

    font["post"].isFixedPitch = 1
    font["OS/2"].recalcAvgCharWidth(font)
    bmp = [cp for cp in codepoints if cp <= 0xFFFF]
    font["OS/2"].usFirstCharIndex = min(bmp)
    font["OS/2"].usLastCharIndex = max(bmp)
    font["maxp"].numGlyphs = len(font.getGlyphOrder())

    font.flavor = "woff2"
    font.save(str(OUT_FONT))
    write_css(OUT_CSS, OUT_FONT.read_bytes())

    print(f"{source} -> {OUT_FONT.relative_to(ROOT)}")
    for codepoint, name, origin, shift in notes:
        extra = f", shifted {shift:+d}" if shift else ""
        print(f"  U+{codepoint:04X} {name:10} {origin}{extra}")
    print(
        f"{len(codepoints)} glyphs ({len(notes)} patched, "
        f"{len(codepoints) - len(notes)} already one cell), "
        f"{OUT_FONT.stat().st_size} bytes; wrote {OUT_CSS.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
